package HelloWorldApp;


/**
* HelloWorldApp/Hello.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Helloworld.idl
* vendredi 24 octobre 2025 11 h 20 WEST
*/

public interface Hello extends HelloOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hello
